apiVersion: v1
kind: Pod
metadata:
  name: pod-web
  labels:
    env: prod
    app: main
    owner: "DiadykAndrii"
spec:
  containers:
    - name: nginx-conteiner
      image: nginx:latest
      ports:
        - containerPort: 80
