---
- name: Install Apache on all servers
  hosts: all
  become: yes
  

  tasks:
  - name: Install Apache
    apt: name=apache2 state=latest

  - name: Start Apache and Enable on boot
    service: name=apache2 state=started enabled=yes
